version: '3.9'

services:
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile  
    restart: always
    stop_grace_period: 5m
    container_name: 'backend'
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./common-blockscout.env
    volumes:
      - ../logs/:/app/logs/